version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortly
    ports:
      - 5432:5432
    networks:
      - shortly_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 6379:6379
    networks:
      - shortly_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

  migrate:
    image: migrate/migrate:latest
    profiles: ["tools"]
    networks:
      - shortly_network
    volumes:
      - ./migrations/:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgresql://postgres:password@postgres:5432/shortly?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

networks:
  shortly_network:
    driver: bridge
volumes:
  postgres_data:
  redis_data:
