database:
  postgres:
    host: localhost
    name: postgres
    port: 5432
    ssl_mode: disable
    query_timeout: 5s
    connect_timeout: 10s
    pool:
      max_conns: 10
      min_conns: 2
      max_conn_lifetime: 1h
      max_conn_idle_time: 15m
      health_check_period: 2m
  redis:
    host: localhost
    port: 6379
    database: 0
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    pool:
      max_idle: 10
      max_active: 100
      idle_timeout: 240s
      max_conn_lifetime: 1h