logging:
  level: debug
  format: console  # json or console
  output: stdout  # stdout, stderr, or file path
  caller: true
  timestamp: true
  timestamp_format: "2006-01-02T15:04:05Z07:00"  # RFC3339 format