security:
  cors:
    allowed_origins:
      - "shortly.praveengongada.com"
      - "http://localhost:3001"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
      - "PATCH"
    allowed_headers:
      - "Accept"
      - "Authorization"
      - "Content-Type"
      - "X-CSRF-Token"
    allow_credentials: true
    max_age: 300  # preflight cache duration in seconds
  request_timeout: 30s