name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: shortly-frontend
  COMPONENT_PATH: ./frontend

jobs:
  verify-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile

      - name: Build Next.js project
        working-directory: ./frontend
        run: yarn build

  build-and-push:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [verify-build]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit hash
        id: commit
        run: |
          # Extract the short commit hash (7 characters)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

          # Set image name with full registry path
          OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "FULL_IMAGE_NAME=${{ env.REGISTRY }}/${OWNER_LOWERCASE}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      # Build and push frontend image
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.COMPONENT_PATH }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.FULL_IMAGE_NAME }}:${{ env.COMMIT_HASH }}
            ${{ env.FULL_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "## Frontend Docker Image Built and Pushed!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Image: ${{ env.FULL_IMAGE_NAME }}:${{ env.COMMIT_HASH }}" >> $GITHUB_STEP_SUMMARY
          echo "Also tagged as: ${{ env.FULL_IMAGE_NAME }}:latest" >> $GITHUB_STEP_SUMMARY
